# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

import flatbuffers

class LneExecOptions(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsLneExecOptions(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LneExecOptions()
        x.Init(buf, n + offset)
        return x

    # LneExecOptions
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LneExecOptions
    def FirmwareSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # LneExecOptions
    def ParameterSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # LneExecOptions
    def IbufferSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # LneExecOptions
    def InputQ(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # LneExecOptions
    def OutputQ(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # LneExecOptions
    def Mean(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            from .mean_vec import mean_vec
            obj = mean_vec()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # LneExecOptions
    def Scale(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # LneExecOptions
    def LneVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # LneExecOptions
    def Fxp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LneExecOptions
    def InFormat(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LneExecOptions
    def OutFormat(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def LneExecOptionsStart(builder): builder.StartObject(11)
def LneExecOptionsAddFirmwareSize(builder, firmwareSize): builder.PrependUint32Slot(0, firmwareSize, 0)
def LneExecOptionsAddParameterSize(builder, parameterSize): builder.PrependUint32Slot(1, parameterSize, 0)
def LneExecOptionsAddIbufferSize(builder, ibufferSize): builder.PrependUint32Slot(2, ibufferSize, 0)
def LneExecOptionsAddInputQ(builder, inputQ): builder.PrependUint32Slot(3, inputQ, 0)
def LneExecOptionsAddOutputQ(builder, outputQ): builder.PrependUint32Slot(4, outputQ, 0)
def LneExecOptionsAddMean(builder, mean): builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(mean), 0)
def LneExecOptionsAddScale(builder, scale): builder.PrependFloat32Slot(6, scale, 0.0)
def LneExecOptionsAddLneVersion(builder, lneVersion): builder.PrependUint32Slot(7, lneVersion, 0)
def LneExecOptionsAddFxp(builder, fxp): builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(fxp), 0)
def LneExecOptionsAddInFormat(builder, inFormat): builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(inFormat), 0)
def LneExecOptionsAddOutFormat(builder, outFormat): builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(outFormat), 0)
def LneExecOptionsEnd(builder): return builder.EndObject()
