# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

import flatbuffers

class mean_vec(object):
    __slots__ = ['_tab']

    # mean_vec
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # mean_vec
    def R(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # mean_vec
    def G(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # mean_vec
    def B(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def Createmean_vec(builder, r, g, b):
    builder.Prep(4, 12)
    builder.PrependFloat32(b)
    builder.PrependFloat32(g)
    builder.PrependFloat32(r)
    return builder.Offset()
